# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
r_packages:
  - covr
warnings_are_errors: true

before_install:
# install packages
- sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
- sudo apt-get --yes --force-yes update -qq
- sudo apt-get install --yes libudunits2-dev
- sudo apt-get install --yes libproj-dev libgeos-dev libgdal-dev

after_success:
  - Rscript -e 'library(covr); codecov()'
